version: "3.9"

services:
  app:
    build: .
    container_name: go-app
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./backend:/app      # mount entire project folder with your binary
    command: ./app  # run your binary inside container
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.rule=PathPrefix(`/api`)
      - traefik.http.services.app.loadbalancer.server.port=8080
  connection:
    build: .
    container_name: go-connection
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./connection:/app      # mount entire project folder with your binary
    command: ./connection  # run your binary inside container
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.connection.entrypoints=web
      - traefik.http.routers.connection.rule=PathPrefix(`/ws`)
      - traefik.http.services.connection.loadbalancer.server.port=8081
  frontend:
    image: node:18-alpine
    container_name: go-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    #ports:
    #  - "5173:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8000
      - REACT_APP_URL=localhost:8000/api 
    command: npm start
    networks:
      - web
#    depends_on:
#      - app
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      #- traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=8000
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data     # <-- referencing the defined volume here
    networks:
      - web

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    networks:
      - web

    healthcheck:
      test: ["CMD", "bash", "-c", " /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true 
     # - traefik.http.middlewares.ratelimit.ratelimit.average=20
     # - traefik.http.middlewares.ratelimit.ratelimit.burst=10
     # - traefik.http.routers.myapp.middlewares=ratelimit
    ports:
      - "8000:80"          # HTTP entry-point (host:8000 -> container:80)
#      - "8080:8080"      # optional: Traefik dashboard on http://localhost:8081
#      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

volumes:
  redis-data:
  kafka-data:

networks:
  web:
    name: traefik-web
